# Generated by Django 4.0 on 2022-06-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='仓库')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='地址')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='User.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('spec', models.CharField(blank=True, max_length=64, null=True, verbose_name='规格')),
                ('price', models.FloatField(verbose_name='销售价')),
                ('batch', models.CharField(blank=True, max_length=64, null=True, verbose_name='批次号')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_set', to='apps.goodscategory', verbose_name='产品分类')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_set', to='apps.goodsunit', verbose_name='产品单位')),
            ],
        ),
    ]
