# Generated by Django 4.0 on 2022-06-25 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('apps', '0003_goods_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeValue', models.CharField(max_length=16, verbose_name='变化数量')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('stockType', models.CharField(choices=[('stockIn', '入库'), ('stockOut', '出库')], max_length=8, verbose_name='流水类型')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockwater', to='apps.goods', verbose_name='商品')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockwater', to='User.customuser')),
            ],
        ),
    ]
